### ISSUE TITLE
`int too big to convert` while calibrating 

### ISSUE THREAD

**Issue by woldmuyn** [twallema/pySODM#3]
## Technical questions

* Python version: 3.10.6
* Operating System: windows / hpc ugent

### Description

During MCMC calibration I sometimes get following error `Python int too large to convert to C long`. 
If i set warmup to 1, the error does not occur 

### What I Did

calibration of PI model
MDC_included = ['01',]
start = '2020-08-01'
end = '2021-10-01'

pars = ['Kp', 'Ki', 'alpha', 'gamma']
labels = ['$K_p$', '$K_i$', '$\\alpha$', '$\\gamma$']
bounds = [(0,10),(0,10),(0,1),(0,1)]
theta = [6.75913708e-04, 9.93008121e-04, 7.32513491e-09, 9.72186282e-02]

```
 File "pandas/_libs/tslibs/timedeltas.pyx", line 372, in pandas._libs.tslibs.timedeltas._maybe_cast_from_unit
  File "pandas/_libs/tslibs/conversion.pyx", line 130, in pandas._libs.tslibs.conversion.cast_from_unit
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/gent/448/vsc44803/anaconda/envs/COVID_MODEL/lib/python3.10/site-packages/emcee/ensemble.py", line 624, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/kyukon/data/gent/448/vsc44803/pySODM/src/pySODM/optimization/objective_functions.py", line 618, in __call__
    out = self.model.sim([self.start_sim,self.end_sim], **simulation_kwargs)
  File "/kyukon/data/gent/448/vsc44803/pySODM/src/pySODM/models/base.py", line 670, in sim
    output.append(self._mp_sim_single(dictionary, time, actual_start_date, method=method, rtol=rtol, l=l))
  File "/kyukon/data/gent/448/vsc44803/pySODM/src/pySODM/models/base.py", line 527, in _mp_sim_single
    out = self._sim_single(time, actual_start_date, method, rtol, l)
  File "/kyukon/data/gent/448/vsc44803/pySODM/src/pySODM/models/base.py", line 494, in _sim_single
    output = solve_ivp(fun, time, y0, args=[self.parameters], t_eval=t_eval, method=method, rtol=rtol)
  File "/data/gent/448/vsc44803/anaconda/envs/COVID_MODEL/lib/python3.10/site-packages/scipy/integrate/_ivp/ivp.py", line 555, in solve_ivp
    solver = method(fun, t0, y0, tf, vectorized=vectorized, **options)
  File "/data/gent/448/vsc44803/anaconda/envs/COVID_MODEL/lib/python3.10/site-packages/scipy/integrate/_ivp/rk.py", line 96, in __init__
    self.h_abs = select_initial_step(
  File "/data/gent/448/vsc44803/anaconda/envs/COVID_MODEL/lib/python3.10/site-packages/scipy/integrate/_ivp/common.py", line 113, in select_initial_step
    f1 = fun(t0 + h0 * direction, y1)
  File "/data/gent/448/vsc44803/anaconda/envs/COVID_MODEL/lib/python3.10/site-packages/scipy/integrate/_ivp/base.py", line 138, in fun
    return self.fun_single(t, y)
  File "/data/gent/448/vsc44803/anaconda/envs/COVID_MODEL/lib/python3.10/site-packages/scipy/integrate/_ivp/base.py", line 20, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "/data/gent/448/vsc44803/anaconda/envs/COVID_MODEL/lib/python3.10/site-packages/scipy/integrate/_ivp/ivp.py", line 527, in <lambda>
    fun = lambda t, x, fun=fun: fun(t, x, *args)
  File "/kyukon/data/gent/448/vsc44803/pySODM/src/pySODM/models/base.py", line 388, in func
    date = self.int_to_date(actual_start_date, t)
  File "/kyukon/data/gent/448/vsc44803/pySODM/src/pySODM/models/base.py", line 538, in int_to_date
    date = actual_start_date + pd.Timedelta(t, unit='D')
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1695, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "pandas/_libs/tslibs/timedeltas.pyx", line 351, in pandas._libs.tslibs.timedeltas.convert_to_timedelta64
  File "pandas/_libs/tslibs/timedeltas.pyx", line 374, in pandas._libs.tslibs.timedeltas._maybe_cast_from_unit
pandas._libs.tslibs.np_datetime.OutOfBoundsTimedelta: Cannot cast 113763.54743547516 from D to 'ns' without overflow.
```

**Comment by twallema** [comment]
Solved by switching to `scipy.solve_ivp()` method `LSODA` @woldmuyn ? I'm closing this issue because its contents are most likely related to the simulated system.
