### ISSUE TITLE
Error performing `df.values` in `__call__()` method of class `log_posterior_probability()` when optimising a model with a timeseries of length 1

### ISSUE THREAD

**Issue by twallema** [twallema/pySODM#63]
I accidently tried optimising a model to a timeseries with only one datapoint,
```python
date
2020-03-15    2753.51636
Name: GDP, dtype: float64
```
Which resulted in an error on the following line in `__call__()` of class `log_posterior_probability()`,
```python
ydata = np.expand_dims(df.squeeze().values,axis=1)
```
Specifically, the `.values` method of `df.squeeze()` does not work and results in the following error,
```bash
AttributeError: 'numpy.float64' object has no attribute 'values'
```
It's a specific situation but I may need to address this at some point.

**Comment by twallema** [comment]
Ran into this one again this year when using pySDOM 0.2.8. I think this needs to return an error message to use two datapoints at a minimum.

```bash
Traceback (most recent call last):
  File "/Users/twa27/Documents/github/Cornell-hierarchDENV/scripts/operational/incremental_forecasting.py", line 151, in <module>
    theta, _ = nelder_mead.optimize(lpp, np.array(theta), len(lpp.expanded_bounds)*[0.2,],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twa27/miniforge3/envs/HIERARCHDENV/lib/python3.12/site-packages/pySODM/optimization/nelder_mead.py", line 121, in optimize
    prev_best = obj(x_start)
                ^^^^^^^^^^^^
  File "/Users/twa27/miniforge3/envs/HIERARCHDENV/lib/python3.12/site-packages/pySODM/optimization/nelder_mead.py", line 17, in _obj_wrapper
    return -func(x, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twa27/miniforge3/envs/HIERARCHDENV/lib/python3.12/site-packages/pySODM/optimization/objective_functions.py", line 321, in __call__
    lp += self.compute_log_likelihood(out, self.states[idx], df, self.weights[idx], self.log_likelihood_fnc[idx], self.log_likelihood_fnc_args[idx], 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twa27/miniforge3/envs/HIERARCHDENV/lib/python3.12/site-packages/pySODM/optimization/objective_functions.py", line 259, in compute_log_likelihood
    ydata = np.expand_dims(df.squeeze().values,axis=1)
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.float64' object has no attribute 'values'
```
